### ISSUE TITLE
TypeError: Cannot read property 'deserializeRawTxnBytes' of undefined

### ISSUE THREAD

**Issue by star0422** [bonustrack/libra-grpc#5]
### Expected behavior
I am trying to get transaction details(sender address, receiver address, amount, ...)
So I tried to deserialize raw transaction data but I fail
### Actual behavior
TypeError: Cannot read property 'deserializeRawTxnBytes' of undefined

**Comment by bonustrack** [comment]
I can't reproduce the issue. How do you import `libra-grpc`? Does it work if you import `libra-grpc/dist/libra.cjs` instead? I think your environment load the esm version.

**Comment by MobileDinero** [comment]
Maybe restack file transfer protocols...?

**Comment by bonustrack** [comment]
We released libra-grpc@0.0.5, this version decode the result of "get_transactions" directly including receiver address and amount.
